### ISSUE TITLE
quotes on linux

### ISSUE THREAD

**Issue by stevecicala** [droodman/julia.ado#3]
Hi David--Many thanks for putting this useful command together. I'm running into issues using on a linux server. Here's what the server administrator had to say:
```

Stata under Linux appears to clobber traditional unix escape characters
and that seems to have an effect on using the julia plugin in stata.
Tested under the following.
Rocky Linux 9 (equivalent to RedHat/EL 9)
Stata version 17, and
Julia veron 1.9.4 (precompiled as distributed - Generic Linux on x86 [64-bit)

       After examining jl.ado, we saw the following line.

         !`1'julia -e "using Libdl; println(dlpath(\"libjulia\"))" > `tempfile'


       The above indicates that stata's ! feature is used to call an external
       programs to test to see if julia is installed and obtain its library path.

       So we tried a much simpler version of something similar:


       Check 1:
       --------
       First start with the verification that when you invoke julia from within stata, it fails.
       -----------------------------------------------------
       . jl: "Hello"
       Unmatched '"'.
       Unmatched '"'.
       Can't access Julia. jl requires that Julia be installed and that you are
       able to start it by typing "julia" in a terminal window (though you won't
       normally need to).
       Installation via juliaup is recommended.
       r(198);
       -----------------------------------------------------


       Check 2:
       --------
       The big clue is the lines Unmatched '"'
       So, tested the following:
       -----------------------------------------------------
        .!julia -e "println(\"Hello\")"

       Unmatched '"'.

       and you can see we get the same error when we directly invoke julia rather
       than via the ado hook/plugin.
       -----------------------------------------------------


       Check 3:
       --------
       The above appears to be a result of improper resolution of quotation
       marks.  So tested the following:
       -----------------------------------------------------
       . !julia -e 'println("Hello")'

       Hello

       .

       Here you can see that this command is executed properly.
       -----------------------------------------------------

       The standard escape character '\' to distinguish the
       double quotation mark of the outside v/s for the inside the println
       function are in use.  That is the normal unix escape character, but
       stata seems to disobey it.
        
       . !julia -e "println(\"Hello\")"
                                     ^      ^
                                 escape chars

       That is the reason the ado is not functional.  It may work on Windows
       environment.

      jl.ado appears to have checks only for Windows and MaOSX environments
      but not others.

```

**Comment by droodman** [comment]
Thanks for this detailed bug report. 

In fact, I find that the current line works in Ubuntu 22.04. And I think the issue is not with Stata, but with variations either in Julia or the OS. Because in testing in Ubuntu, Windows, and macOS, whichever version(s) work in Stata are the ones that also work directly from the shell. Mac and Ubuntu can handle both ways. Windows can only handle it with `"`. Apparently RH Linux can only handle it with `'`. 

I think the safest thing is for the code to try it both ways.

Please try the new release:
```
net install julia, replace from(https://raw.github.com/droodman/julia.ado/v0.7.1)
```
...then restart Stata. Please reopen this issue if it doesn't work.

**Comment by stevecicala** [comment]
Thank you David, I'm Cc'ing Mohan, who administers the server in question.

Here is my last exchange with him, still coming up with an error:

Attached zipped file contains logs. I am running a very simple 2 line
stata code:

set trace on
jl: "Hello!"

Normally, this should just spit out "Hello!"  We have demonstrated that
using ! julia -e 'println("Hello!")' from within stata.

But I get a segmentation fault core dump error.  So I added tracing in
stata.
Attached zipped file contains the .do file, .log file, and .stderr file.

BTW, the stata ado for julia is version "jl 0.7.1 8 December 2023" that is
installed.

**Comment by droodman** [comment]
Thanks Steve. Did you forget the attachment? Or maybe it doesn't come through when we engage in issue threads via email.

**Comment by droodman** [comment]
Also, for what it’s worth, try going to version 0.7.2 of the Julia plugin:

```
net install julia, replace from(https://raw.github.com/droodman/julia.ado/v0.7.2)
```

**Comment by droodman** [comment]
This is a mystery.

I was unable to reproduce the problem under Pengwin Enterprise 9 Linux under Windows, which I gather is closely related to RH Linux.

The log file shows that it successfully executes the Julia command `using stataplugininterface` via
```
plugin call _julia , evalqui `" using stataplugininterface"'
```
but then crashes on
```
plugin call _julia , evalqui `" using DataFrames"'
```

Let me know if upgrading to 0.7.2 helps, at least by giving an error message instead of crashing.

**Comment by droodman** [comment]
Another thing you could try--though I'd be surprised if it helps--is to recompile the plugin on that system. The source code is at [https://raw.github.com/droodman/julia.ado/v0.7.2/cpp](https://github.com/droodman/julia.ado/tree/master/cpp). You would just download the three files, cd to the download folder, and do something like
```
JULIA_DIR=/home/droodman/.julia/juliaup/julia-1.9.4+0.x64.linux.gnu
g++ -shared -fPIC -DSYSTEM=OPUNIX stplugin.c julia.ado.cpp -o jl.plugin -I$JULIA_DIR/include/julia
```
The first line of course needs to point to where Julia is installed. The folder it points to should have an `include` subfolder.

Then in Stata, type `where jl` to see where Stata stores files beginning with "j". Then copy the compiled file, jl.plugin, to that folder, and restart Stata.
