### ISSUE TITLE
Could not load plugin

### ISSUE THREAD

**Issue by reisportela** [droodman/julia.ado#5]
Dear David,
thank you for your command.
I am running an Ubuntu 20.04 with Julia 1.94., and exploring reghdfejl. Typing `which jl` I get version 0.8.0 28 December.
Typing `jl` I get the following error: 

Could not load plugin: /usr/local/stata18/ado/plus/j/jl.plugin
(error occurred while loading jl.ado)

I confirmed that the `jl.plugin`is located here: /usr/local/stata18/ado/plus/j/

I installed julia.ado using

require julia, install from("https://raw.githubusercontent.com/labordynamicsinstitute/ssc-mirror/2024-01-15/fmwww.bc.edu/repec/bocode/`first'")

Could you please let me know how I can sove this issue?

Thank you, miguel

**Comment by droodman** [comment]
In that `requires` command line, what is the value of the `first` macro?

Did you try the simpler
```
ssc install julia, replace
```

**Comment by reisportela** [comment]
thank you very much for the reply

I have the same problem, both using `ssc install julia, replace`, or `
net install julia, replace from(https://raw.github.com/droodman/julia.ado/v0.5.8)`

the require "replicates" the net install, but allows to set a "frozen" repository

**Comment by droodman** [comment]
Interesting. I've been compiling in Ubuntu 22.04 and the result doesn't run in Ubuntu 20.04. But compiling in 20.04 seems to work in both Ubuntu's, Debian, and Pengwin.

Can you try this?
```
 net install julia, replace from(https://raw.github.com/droodman/julia.ado/v0.8.1)
```
Then restart Stata.

**Comment by reisportela** [comment]
thank you very much. jl now loads the plugin. running `jl: sqrt(2)` Stata crashes, but I am almost sure the problem is on my side, probably due to the installation of Julia, I am analysing the problem and will post here the solution

fast context. I am building a singularity container running Ubuntu 20.04 that has inside Stata 18 and Julia, and I want to use `reghdfejl` with a GPU. it might be the case that in the building process I miss some library, or Julia package

**Comment by droodman** [comment]
Excellent. You probably don't need the advice, but just in case: I would
see if you can execute the examples at
https://github.com/FixedEffects/FixedEffectModels.jl directly in Julia.
