### ISSUE TITLE
Using Factor Notation

### ISSUE THREAD

**Issue by friosavila** [droodman/julia.ado#7]
Good morning,
I was playing a bit with reghdfejl and encounter a problem when using factor notation.
Specifically, consider the following example

```
 use http://fmwww.bc.edu/RePEc/bocode/o/oaxaca.dta, clear
reghdfejl lnwage educ , abs(age)
reghdfejl lnwage c.educ , abs(age)
reghdfejl lnwage c.educ##c.educ , abs(age)
```
The first two cases work, but the last one doesn't, providing the warnings

```
invalid syntax
invalid varname
```

For reference i have the following installed

```
. which jl.ado
c:\ado\plus\j\jl.ado
*! jl 1.0.0 12 April 2024
*! Copyright (C) 2023-24 David Roodman

. which reghdfejl.ado
c:\ado\plus\r\reghdfejl.ado
*! reghdfejl 1.0.0 12 April 2024

```

Thank you
Fernando

**Comment by droodman** [comment]
Thanks for the bug report, @friosavila.

I just fixed it, I think. I'll have the new version posted to SSC. For now you can install it from GitHub:
```net install reghdfejl, replace from(https://raw.github.com/droodman/reghdfejl/v1.0.1)```

Oh, and actually the new version will also need version 1.0.1 of the `julia` package. So also do:
```net install julia, replace from(https://raw.github.com/droodman/julia.ado/v1.0.01)```

**Comment by friosavila** [comment]
Thank you!
Yes, it now works with the original example (c.educ##c.educ)
Nowever, it does not work if I combine c. with i.

```
reghdfejl lnwage c.educ##i.female , abs(age)
```

Thank you

**Comment by droodman** [comment]
Apologies.
Try this one:
```
net install reghdfejl, replace from(https://raw.github.com/droodman/reghdfejl/v1.0.2)
```
