### ISSUE TITLE
reghdfejl crashes with 1.1.0

### ISSUE THREAD

**Issue by psungho** [droodman/julia.ado#8]
Not only does it crash, stata refuses after reloading, to open jl.plugin (it says ./jl.plugin cannot be opened or smth like that)

it works w/ 1.0.2

**Comment by droodman** [comment]
Is this on a Mac?
I am working on a Mac issue now. Unfortunately, the arrival of Julia 1.11 broke this package. It turns out there is no stability guarantee for Julia's low-level, C-based interface.

**Comment by droodman** [comment]
Very sorry. I _think_ I have fixed an issue on Macs with Apple silicon. If that is what you are using, install the latest version with
```
net install julia, replace from(https://raw.github.com/droodman/julia.ado/v1.1.1)
```
And then restart Stata. Let me know if it works or not.

**Comment by droodman** [comment]
I believe release 1.1.2 fixes this issue.
